debian/rules: split up subshell content onto unique lines and fix bash syntax error near "exit 1".

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -30,7 +30,11 @@ override_dh_auto_configure:
 		if [ -d  ../../patches.xorg/$$XORG_UPSTREAM_VERSION ]; then \
 			QUILT_PATCHES=../../patches.xorg/$${XORG_UPSTREAM_VERSION}/ quilt push -a; \
 		else \
-			( set +x; echo "\n##################################################\nERROR: This X2Go KDrive version does not support\nbuilding against X.Org version $$XORG_UPSTREAM_VERSION.\n##################################################\n"; exit 1); \
+			( \
+				set +x; \
+				echo "\n##################################################\nERROR: This X2Go KDrive version does not support\nbuilding against X.Org version $$XORG_UPSTREAM_VERSION.\n##################################################\n"; \
+				exit 1; \
+			); \
 		fi
 
 	# run autoreconf
